---
# services
- service:
   name: docker
   state: started
- user:
    name: "{{ syncthing_owner }}"
    uid: "{{ syncthing_owner_id }}"
- group:
    name: "{{ syncthing_group }}"
    gid: "{{ syncthing_group_id }}"

 
# build directory and resources
- file:
    path: "{{ syncthing_build_dir }}"
    state: directory
    recurse: yes
    owner: "{{ syncthing_owner }}"
    group: docker
- name: copy build recipe and ingredients
  copy:
    src: "{{ item }}"
    dest: "{{ syncthing_build_dir }}"
  with_items:
    - Dockerfile
    - docker-entrypoint.sh
    - setuidgid.inc
- name: set permissions on copied ingredients
  file:
    path: "{{ syncthing_build_dir }}/docker-entrypoint.sh"
    mode: 0755
- template:
    src: nginx-location.conf.j2
    dest: "{{ syncthing_build_dir }}/nginx-location.conf"

# share root and shared directories
- file:
    path: "{{ syncthing_share_root }}/{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ syncthing_owner }}"
    group: "{{ syncthing_group }}"
  with_items: "{{ syncthing_make_shared_dirs }}"
- file:
    path: "{{ syncthing_config_destination_dir }}"
    state: directory
    recurse: yes
    owner: "{{ syncthing_owner }}"
    group: "{{ syncthing_group }}"
- name: copy configuration and key material
  copy:
    src: "{{ syncthing_config_source_dir }}/{{ item }}"
    dest: "{{ syncthing_config_destination_dir }}"
    owner: "{{ syncthing_owner }}"
    group: "{{ syncthing_group }}"
    mode: 0400
  with_items:
    - cert.pem
    - key.pem
    - config.xml
- docker_image:
    name: timcinel/syncthing
    tag: latest
    path: "{{ syncthing_build_dir }}"
- set_fact:
    syncthing_docker_volumes:
      - "{{ syncthing_config_destination_dir }}:/home/syncthing/.config/syncthing"
      - "{{ syncthing_share_root }}:{{ syncthing_share_root }}"
- docker_container:
    name: syncthing
    image: timcinel/syncthing
    state: started
    restart_policy: always
    volumes: "{{ syncthing_docker_volumes }}"
    published_ports: "{{ syncthing_docker_ports }}"
    env:
      DOCKER_USER: "syncthing"
      DOCKER_USER_ID: "{{ syncthing_owner_id }}"
      DOCKER_GROUP: "syncthing"
      DOCKER_GROUP_ID: "{{ syncthing_group_id }}"
    memory: "{{ syncthing_memory_limit }}"
    networks:
      - name: "{{ syncthing_docker_network }}"
- docker_container:
    name: syncthing-locations-data
    image: alpine
    state: stopped
    volumes:
      - "{{ syncthing_build_dir }}/nginx-location.conf:{{ syncthing_nginx_vhost_locationsd_dir }}/location.conf"
    command: /bin/true
